name: test123
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  intl: ^0.18.1
  firebase_storage: ^11.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  firebase_storage: ^11.2.7
  flutter_secure_storage: ^9.0.0
  modal_progress_hud_nsn: ^0.4.0
  flutter_chat_bubble: ^2.0.2
  image_picker: ^1.0.4

flutter:
  uses-material-design: true
  assets:
   - lib/chat_app/image/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
